services:
  - type: web
    name: solutions-binary
    runtime: static
    staticPublishPath: .
    buildCommand: ""
    pullRequestPreviewsEnabled: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
